services:
  db:
    image: postgres:16-alpine
    container_name: zakupai-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-zakupai}
      POSTGRES_USER: ${POSTGRES_USER:-zakupai}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-zakupai}
    ports:
      - "5433:${POSTGRES_PORT:-5432}"   # host:container
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-zakupai} -d ${POSTGRES_DB:-zakupai}"]
      interval: 5s
      timeout: 3s
      retries: 20

  calc-service:
    build: ./services/calc-service
    container_name: zakupai-calc
    env_file: .env
    environment:
      PORT: ${CALC_PORT:-8001}
      API_KEY: ${API_KEY:-changeme}
      DB_URL: ${DB_URL:-postgresql://zakupai:zakupai@zakupai-db:5432/zakupai}
    ports:
      - "${CALC_PORT:-8001}:${CALC_PORT:-8001}"
    depends_on:
      db:
        condition: service_healthy

  risk-engine:
    build: ./services/risk-engine
    container_name: zakupai-risk
    env_file: .env
    environment:
      PORT: 8000
      API_KEY: ${API_KEY:-changeme}
      DB_URL: ${DB_URL:-postgresql://zakupai:zakupai@zakupai-db:5432/zakupai}
    ports:
      - "${RISK_PORT:-8002}:8000"
    depends_on:
      db:
        condition: service_healthy

  doc-service:
    build: ./services/doc-service
    container_name: zakupai-doc
    env_file: .env
    environment:
      PORT: ${DOC_PORT:-8003}
      API_KEY: ${API_KEY:-changeme}
      DB_URL: ${DB_URL:-postgresql://zakupai:zakupai@zakupai-db:5432/zakupai}
      DB_HOST: zakupai-db
    ports:
      - "8003:8000"
    depends_on:
      db:
        condition: service_healthy

  embedding-api:
    build: ./services/embedding-api
    container_name: zakupai-emb
    env_file: .env
    environment:
      PORT: ${EMB_PORT:-8004}
      API_KEY: ${API_KEY:-changeme}
      DB_URL: ${DB_URL:-postgresql://zakupai:zakupai@zakupai-db:5432/zakupai}
      DB_HOST: zakupai-db
    ports:
      - "8004:8000"
    depends_on:
      db:
        condition: service_healthy

  gateway:
    image: nginx:alpine
    container_name: zakupai-gateway
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - calc-service
      - risk-engine
      - doc-service
      - embedding-api

volumes:
  pgdata:
