services:
  promtail:
    image: grafana/promtail:2.9.0
    container_name: zakupai-promtail-stage6
    profiles: ['stage6']
    command: >
      -config.file=/etc/promtail/promtail-config.yml
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./monitoring/promtail-config.yml:/etc/promtail/promtail-config.yml:ro
    networks:
      - zakupai-network
    restart: unless-stopped

networks:
  zakupai-network:
    external: false
