route:
  receiver: 'telegram'
  group_by: ['alertname', 'service']
  group_wait: 10s
  group_interval: 2m
  repeat_interval: 1h

receivers:
  - name: 'telegram'
    webhook_configs:
      - url: 'http://alertmanager-bot:8080/alert'
        send_resolved: true
