global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: gateway
    metrics_path: /metrics
    static_configs:
      - targets: ['gateway:8000']
  - job_name: risk-engine
    metrics_path: /metrics
    static_configs:
      - targets: ['risk-engine:8000']
  - job_name: calc-service
    metrics_path: /metrics
    static_configs:
      - targets: ['calc-service:8000']
