global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alerts.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: gateway
    metrics_path: /metrics
    static_configs:
      - targets: ['gateway:80']

  - job_name: embedding-api
    metrics_path: /metrics
    static_configs:
      - targets: ['embedding-api:8000']

  - job_name: calc-service
    metrics_path: /metrics
    static_configs:
      - targets: ['calc-service:8000']

  - job_name: risk-engine
    metrics_path: /metrics
    static_configs:
      - targets: ['risk-engine:8000']

  - job_name: doc-service
    metrics_path: /metrics
    static_configs:
      - targets: ['doc-service:8000']

  - job_name: billing-service
    metrics_path: /metrics
    static_configs:
      - targets: ['billing-service:8000']

  - job_name: etl-service
    metrics_path: /metrics
    static_configs:
      - targets: ['etl-service:8000']

  - job_name: web-ui
    metrics_path: /metrics
    static_configs:
      - targets: ['web-ui:8000']

  - job_name: goszakup-api
    metrics_path: /metrics
    static_configs:
      - targets: ['goszakup-api:8001']

  - job_name: node-exporter
    static_configs:
      - targets: ['node-exporter-stage6:9100']

  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:8080']
