server:
  http_listen_port: 0
  grpc_listen_port: 0

positions:
  filename: /tmp/promtail-positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 30s
        filters:
          - name: network
            values: [zakupai_zakupai-network]
    pipeline_stages:
      - docker: {}
      - labels:
          job:
          container:
          service:
          compose_project:
    relabel_configs:
      # Устанавливаем job по умолчанию
      - target_label: job
        replacement: docker
      # Извлекаем имя контейнера
      - source_labels: [__meta_docker_container_name]
        regex: /?(.+)
        target_label: container
        replacement: $1
      # Извлекаем service из compose label
      - target_label: service
        replacement: unknown
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        regex: (.+)
        target_label: service
        replacement: $1
      # Извлекаем compose_project
      - source_labels: [__meta_docker_container_label_com_docker_compose_project]
        regex: (.+)
        target_label: compose_project
        replacement: $1
      # Добавляем __path__ для чтения логов
      - source_labels: [__meta_docker_container_log_stream]
        target_label: __path__
