version: "3.8"

services:
  # Workflow Scheduler (for cron-like tasks)
  zakupai-scheduler:
    image: mcuadros/ofelia:latest
    container_name: zakupai-scheduler
    restart: unless-stopped
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - zakupai-network
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.lot-scanner.schedule: "0 9,14,18 * * *"
      ofelia.job-exec.lot-scanner.container: "zakupai-n8n"
      ofelia.job-exec.lot-scanner.command: 'curl -X POST "http://localhost:5678/webhook/daily-lot-scanner" -H "Content-Type: application/json"'
      ofelia.job-exec.price-monitor.schedule: "0 6,12,20 * * *"
      ofelia.job-exec.price-monitor.container: "zakupai-n8n"
      ofelia.job-exec.price-monitor.command: 'curl -X POST "http://localhost:5678/webhook/price-monitor" -H "Content-Type: application/json"'
      ofelia.job-exec.health-check.schedule: "*/10 * * * *"
      ofelia.job-exec.health-check.container: "zakupai-n8n"
      ofelia.job-exec.health-check.command: 'curl -X GET "http://localhost:5678/healthz"'

networks:
  zakupai-network:
    name: zakupai_zakupai-network
    external: true
