groups:
  - name: zakupai_infrastructure
    rules:
      - alert: HighCPUUsage
        expr: (100 - avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m]) * 100)) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "Average CPU usage exceeded 80% for more than 5 minutes."

  - name: zakupai_application
    rules:
      - alert: ApiErrorBurst
        expr: sum by (service) (increase(http_requests_total{status=~"5.."}[1m])) >= 5
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "HTTP 5xx burst on {{ $labels.service }}"
          description: "Detected at least 5 HTTP 5xx responses within the last minute."

  - name: zakupai_business
    rules:
      - alert: AntiDumpingRateHigh
        expr: zakupai_antidumping_rate > 0.15
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Anti-dumping rate exceeds 15%"
          description: "Business metric zakupai_antidumping_rate is above 15% for 10 minutes."
