groups:
  - name: zakupai_api_slo
    rules:
      - record: api_error_ratio
        expr: |
          sum(rate(http_requests_total{status_code=~"5.."}[5m])) by (service)
            /
          clamp_min(sum(rate(http_requests_total[5m])) by (service), 1e-6)
      - record: api_p95_latency
        expr: |
          histogram_quantile(
            0.95,
            sum(rate(http_request_duration_seconds_bucket[5m])) by (le, service)
          )
