# syntax=docker/dockerfile:1.6
# ✅ используем минимальный рабочий образ, в котором есть базовые команды
FROM alpine:3.18 AS libs

# копируем общую библиотеку внутрь контейнера
COPY zakupai_common /zakupai_common

