apiVersion: 1

datasources:
  - name: Prometheus
    uid: zakupai-prom
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: GET
      timeInterval: 30s

  - name: Loki
    uid: zakupai-loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
