apiVersion: 1
datasources:
  - name: Prometheus
    uid: zakupai-prom
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: true
  - name: Loki
    uid: zakupai-loki
    type: loki
    url: http://loki:3100
    access: proxy
