---
name: ci-optimized
# 'on':
#   push: {}
#   pull_request: {}
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read
  security-events: write
env:
  PYTHON_VERSION: '3.11'
  PIP_CACHE_DIR: ~/.cache/pip
  APT_CACHE_DIR: ~/.cache/apt

jobs:
  fast-checks:
    if: false  # Stage7 refactor: workflow consolidated into ci.yml
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        check:
          - lint
          - compose-config
          - security
    steps:
      # Original fast-check steps retained for reference.
      # - uses: actions/checkout@v4
      # - name: Setup Python (for lint and security)
      #   if: matrix.check != 'compose-config'
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: ${{ env.PYTHON_VERSION }}
      # - name: Cache pip dependencies
      #   if: matrix.check != 'compose-config'
      #   uses: actions/cache@v4
      #   with:
      #     path: ${{ env.PIP_CACHE_DIR }}
      #     key: pip-${{ runner.os }}-${{ matrix.check }}-${{ hashFiles('**/requirements.txt', '.pre-commit-config.yaml') }}
      #     restore-keys: |
      #       pip-${{ runner.os }}-${{ matrix.check }}-
      #       pip-${{ runner.os }}-
      - run: echo "fast-checks workflow disabled during Stage7 refactor"

  build-services:
    if: false  # Stage7 refactor: workflow consolidated into ci.yml
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service:
          - calc-service
          - risk-engine
          - doc-service
          - embedding-api
          - etl-service
    steps:
      # - uses: actions/checkout@v4
      # - uses: docker/setup-qemu-action@v3
      # - uses: docker/setup-buildx-action@v3
      - run: echo "build-services workflow disabled during Stage7 refactor"

  setup-database:
    if: false  # Stage7 refactor: workflow consolidated into ci.yml
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v4
      - run: echo "setup-database workflow disabled during Stage7 refactor"

  test-matrix:
    if: false  # Stage7 refactor: workflow consolidated into ci.yml
    runs-on: ubuntu-latest
    needs:
      - fast-checks
      - setup-database
    strategy:
      fail-fast: false
      matrix:
        test-suite:
          - name: unit-tests
            cache-key: unit
            services: db
            install-tesseract: false
          - name: etl-smoke
            cache-key: etl
            services: db
            install-tesseract: false
          - name: etl-upload
            cache-key: etl-full
            services: db
            install-tesseract: true
          - name: priority3-e2e
            cache-key: priority3
            services: db chromadb embedding-api etl-service goszakup-api n8n
            install-tesseract: true
          - name: web-ui-integration
            cache-key: webui
            services: db etl-service
            install-tesseract: false
          - name: webui-e2e
            cache-key: webui-full
            services: db goszakup-api etl-service chromadb web-ui
            install-tesseract: true
    steps:
      - run: echo "test-matrix workflow disabled during Stage7 refactor"

  smoke-tests:
    if: false  # Stage7 refactor: workflow consolidated into ci.yml
    runs-on: ubuntu-latest
    needs:
      - build-services
      - setup-database
    strategy:
      fail-fast: false
      matrix:
        service:
          - calc
          - risk
          - doc
          - emb
    steps:
      - run: echo "smoke-tests workflow disabled during Stage7 refactor"

  ci-summary:
    if: false  # Stage7 refactor: workflow consolidated into ci.yml
    runs-on: ubuntu-latest
    needs:
      - fast-checks
      - build-services
      - test-matrix
      - smoke-tests
    # if: always()
    steps:
      - run: echo "ci-summary workflow disabled during Stage7 refactor"
