name: ci

on:
  push: {}
  pull_request: {}

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install ruff black

      - name: Ruff (lint)
        run: ruff check services

      - name: Black (format check)
        run: black --check services

  compose_sanity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker Compose config
        run: docker compose config -q

  build:
    runs-on: ubuntu-latest
    needs: precommit
    concurrency:
      group: ci-build-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      matrix:
        svc: ["calc-service", "risk-engine", "doc-service", "embedding-api", "etl-service"]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Build ${{ matrix.svc }}
        uses: docker/build-push-action@v6
        with:
          context: ./services/${{ matrix.svc }}
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false

  precommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml', '**/requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-
      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
      - name: Run pre-commit
        run: pre-commit run --all-files

  migrate:
    runs-on: ubuntu-latest
    needs: precommit
    steps:
      - uses: actions/checkout@v4
      - name: Start database
        run: docker compose up -d db
      - name: Run migrations
        run: docker compose run --rm migrator
      - name: Stop containers
        run: docker compose down

  pytest:
    runs-on: ubuntu-latest
    needs: migrate
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-
      - name: Install common lib
        run: pip install -e libs/zakupai_common
        if: github.event_name == 'push' || github.event_name == 'pull_request'
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          find services -name requirements.txt -exec pip install -r {} \;
          pip install pytest pytest-cov ruff black isort bandit
      - name: Run linters
        run: |
          ruff check .
          black --check .
          isort --check-only .
      - name: Run security checks
        run: bandit -r services libs -lll
      - name: Run tests
        run: pytest -q --cov=services --cov=libs --cov-report=term --disable-warnings

  deploy:
    runs-on: ubuntu-latest
    needs: [pytest, bandit-scan]
    if: github.ref == 'refs/heads/refactor/common-lib-test' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker images
        run: |
          docker build -t zakupai/gateway:stage5 -t zakupai/gateway:latest --build-arg TAG=stage5 ./services/gateway
          docker build -t zakupai/etl-service:stage5 -t zakupai/etl-service:latest --build-arg TAG=stage5 ./services/etl-service
          docker build -t zakupai/risk-engine:stage5 -t zakupai/risk-engine:latest --build-arg TAG=stage5 ./services/risk-engine
          docker build -t zakupai/calc-service:stage5 -t zakupai/calc-service:latest --build-arg TAG=stage5 ./services/calc-service
          docker build -t zakupai/embedding-api:stage5 -t zakupai/embedding-api:latest --build-arg TAG=stage5 ./services/embedding-api
          docker build -t zakupai/bot:stage5 -t zakupai/bot:latest --build-arg TAG=stage5 ./bot
          docker push zakupai/gateway:stage5
          docker push zakupai/gateway:latest
          docker push zakupai/etl-service:stage5
          docker push zakupai/etl-service:latest
          docker push zakupai/risk-engine:stage5
          docker push zakupai/risk-engine:latest
          docker push zakupai/calc-service:stage5
          docker push zakupai/calc-service:latest
          docker push zakupai/embedding-api:stage5
          docker push zakupai/embedding-api:latest
          docker push zakupai/bot:stage5
          docker push zakupai/bot:latest

      - name: Setup SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ${{ runner.temp }}/ssh_key
          chmod 600 ${{ runner.temp }}/ssh_key

      - name: Deploy to staging
        run: |
          ssh -o ConnectTimeout=30 -o StrictHostKeyChecking=no -i ${{ runner.temp }}/ssh_key user@staging "cd /path/to/zakupai && export TAG=stage5 && docker compose -f docker-compose.yml -f docker-compose.override.prod.yml pull && docker compose -f docker-compose.yml -f docker-compose.override.prod.yml up -d --timeout 60"

      - name: Rollback on failure
        if: failure()
        run: |
          ssh -o ConnectTimeout=30 -o StrictHostKeyChecking=no -i ${{ runner.temp }}/ssh_key user@staging "cd /path/to/zakupai && export TAG=stable && docker compose -f docker-compose.yml -f docker-compose.override.prod.yml up -d --timeout 60"

  smoke-matrix:
    runs-on: ubuntu-latest
    needs: [migrate, build]
    strategy:
      matrix:
        service: [calc, risk, doc, emb]
    steps:
      - uses: actions/checkout@v4
      - name: Start db
        run: docker compose up -d db
      - name: Start ${{ matrix.service }} service
        run: |
          case "${{ matrix.service }}" in
            calc) docker compose up -d calc-service ;;
            risk) docker compose up -d risk-engine ;;
            doc) docker compose up -d doc-service ;;
            emb) docker compose up -d embedding-api ;;
          esac
      - name: Wait for service health
        run: |
          case "${{ matrix.service }}" in
            calc) port=8001 ;;
            risk) port=8002 ;;
            doc) port=8003 ;;
            emb) port=8004 ;;
          esac
          timeout 90 bash -c "until curl -fsS http://localhost:$port/health; do sleep 3; done"
      - name: Run smoke test
        run: bash scripts/smoke.sh

  etl-smoke-test:
    runs-on: ubuntu-latest
    needs: migrate
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-etl-${{ hashFiles('services/etl-service/requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-etl-
      - name: Start database
        run: docker compose up -d db
      - name: Wait for database
        run: timeout 60 bash -c "until docker compose exec db pg_isready -U zakupai; do sleep 2; done"
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          cd services/etl-service
          pip install psycopg2-binary python-dotenv
      - name: Run ETL smoke test
        run: |
          cd services/etl-service
          chmod +x smoke_test.sh
          ./smoke_test.sh
        env:
          PGPASSWORD: zakupai
      - name: Upload smoke test logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: etl-smoke-test-logs
          path: |
            services/etl-service/smoke_test.log
            services/etl-service/ocr_loader.log
          retention-days: 7

  bandit-scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install bandit
        run: pip install bandit
      - name: Run bandit (SARIF)
        run: bandit -q -r services -f sarif -o bandit.sarif
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: bandit.sarif
