name: ci

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install ruff black

      - name: Ruff (lint)
        run: ruff check services

      - name: Black (format check)
        run: black --check services

  compose_sanity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker Compose config
        run: docker compose config -q

  build:
    runs-on: ubuntu-latest
    needs: [lint, compose_sanity]
    strategy:
      matrix:
        svc:
          - services/calc-service
          - services/risk-engine
          - services/doc-service
          - services/embedding-api
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build ${{ matrix.svc }}
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.svc }}
          push: false
